import {CardData} from './card-data';

export const CARDDATA: CardData[] = [
  {
    id: 1,
    name: 'Bobert',
    jobTitle: 'Musician',
    company: 'Guitar Center',
    addressLine1: '101 road street',
    addressLine2: '',
    city: 'Washington',
    state: 'OH',
    zipcode: '99999',
    imagePath: '',
    dateCreated: 'Today',
    dateUpdated: 'Today',
    owner: null,
    users: null
  },
  {
    id: 2,
    name: 'Bobert',
    jobTitle: 'Musician',
    company: 'Theater of the Living Arts',
    addressLine1: '101 road street',
    addressLine2: '',
    city: 'Washington',
    state: 'OH',
    zipcode: '99999',
    imagePath: '',
    dateCreated: 'Today',
    dateUpdated: 'Today',
    owner: null,
    users: null
  },
  {
    id: 3,
    name: 'Bobert',
    jobTitle: 'Musician',
    company: '',
    addressLine1: '101 road street',
    addressLine2: '',
    city: 'Washington',
    state: 'OH',
    zipcode: '99999',
    imagePath: '',
    dateCreated: 'Today',
    dateUpdated: 'Today',
    owner: null,
    users: null
  },
  {
    id: 4,
    name: 'Bobert',
    jobTitle: 'Musician',
    company: '',
    addressLine1: '101 road street',
    addressLine2: '',
    city: 'Washington',
    state: 'OH',
    zipcode: '99999',
    imagePath: '',
    dateCreated: 'Today',
    dateUpdated: 'Today',
    owner: null,
    users: null
  },
  {
    id: 5,
    name: 'Bobert',
    jobTitle: 'Musician',
    company: '',
    addressLine1: '101 road street',
    addressLine2: '',
    city: 'Washington',
    state: 'OH',
    zipcode: '99999',
    imagePath: '',
    dateCreated: 'Today',
    dateUpdated: 'Today',
    owner: null,
    users: null
  },
  {
    id: 6,
    name: 'Bobert',
    jobTitle: 'Musician',
    company: '',
    addressLine1: '101 road street',
    addressLine2: '',
    city: 'Washington',
    state: 'OH',
    zipcode: '99999',
    imagePath: '',
    dateCreated: 'Today',
    dateUpdated: 'Today',
    owner: null,
    users: null
  },
  {
    id: 7,
    name: 'Bobert',
    jobTitle: 'Musician',
    company: '',
    addressLine1: '101 road street',
    addressLine2: '',
    city: 'Washington',
    state: 'OH',
    zipcode: '99999',
    imagePath: '',
    dateCreated: 'Today',
    dateUpdated: 'Today',
    owner: null,
    users: null
  },
  {
    id: 8,
    name: 'Bobert',
    jobTitle: 'Musician',
    company: '',
    addressLine1: '101 road street',
    addressLine2: '',
    city: 'Washington',
    state: 'OH',
    zipcode: '99999',
    imagePath: '',
    dateCreated: 'Today',
    dateUpdated: 'Today',
    owner: null,
    users: null
  }
];
